### PR TITLE
added the starter for the views

### PR DESCRIPTION
**Pull request by piazzaana**
Added templates for pages, testing pull request

### CODE REVIEW

**Comment by reactivepixel** [comment]
Looks like this pull request is erroneous from the standpoint of all of your content is already in the master branch. The better way is to push the feature branch up to github and then make a pull request from the feature branch to the dev branch. Then the weekly release would be from the dev branch to the Release branch.

**Comment by reactivepixel** [comment]
That aside here are some issues I see:

**.idea folder in the repo.**
This folder is specific to your personal IDE settings and should not be considered part of your code base. .gitignore it and remove it from your repo.

**Readme**
This should detail various portions of your project so that others can understand what this code base would be (example would be a potential employer reviewing this code base). It should also have much of the information from your project spec, detailing the technologies in use, and any procedures needed to install the code base. Check out [this template](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2) regarding getting started in that area.

**Semantic Folder Names**
It's hard to tell what the difference between ```./chicken-fires``` and ```./wp-chicken-fires``` will be. WP can be assumed word press, but the other folder seems to be a node project and it is confusing if this is intended or if you accidentally have multiple repos inside of this main repo. Here's a [further explanation](https://www.youtube.com/watch?v=H27HucyujUg&t=0s&list=PLEBnLDjR5B912lpuj_8kkqx8zxiiXQB61&index=2) of this issue. If you have multiple components in your project that are running simultaneously reach out to me and we can discuss how best to handle this. (Example would be a bot, a front end, and a db that all are working in tandem in the same repo for easy management)

**Dependencies**
These should not be in your repo, ignore and remove them. Here's [further clarification](https://www.youtube.com/watch?v=iF9W8CeCfNM&index=4&list=PLEBnLDjR5B912lpuj_8kkqx8zxiiXQB61) on this issue.

**Comment by piazzaana** [comment]
Added .idea and node_modules to .gitignore and removed from repo, working on the other issues.

**Comment by piazzaana** [comment]
Hi Chris, the idea of the wp-chicken-fries folder was to handle CMS with wordpress, but I'll add that at a later point and I removed the folder from the repo to avoid confusion. Check it out. Thanks

**Pull request closed without merging**
